enum routeMapMini {
  login = "/login",
  dashboard = "/dashboard",
  payin = "/payin",
  settlement = "/settlement",
  payout = "/payout",
  technical = "/technical",
  merchantManagement = "/merchant-management",
  complainceSecurity = "/complaince-security",
  reseller = "/reseller",
  reports = "/reports",
  accessManagement = "/access-management",
  detailedTransactions = "/payin/detailed-transactions",
  updateTransactions = "/payin/update-transactions",
  checkStatus = "/payin/check-status",
  detailedSettlementTransactions = "/settlement/detailed-settlement-transactions",
  bulkAdjustment = "/settlement/bulk-adjustment",
  chargebackRefund = "/settlement/chargeback-refund",
  settlementStatement = "/settlement/settlement-statement",
  myAccount = "/my-account",
  payoutDetailedTransactions = "/payout/detailed-transactions",
  accounts = "/payout/accounts",
  statement = "/payout/statement",
  merchantManagementStep1 = "/merchant-management-step1",
  merchantManagementStep2 = "/merchant-management-step2",
  merchantManagementStep3 = "/merchant-management-step3",
  merchantManagementStep4 = "/merchant-management-step4",
  merchantManagementStep5 = "/merchant-management-step5",
  merchantManagementStep6 = "/merchant-management-step6",
  merchantDetailsPage = "/merchant-management/merchant-details-page",
  merchantRoutingConfig = "/merchant-management/merchant-routing-config",
  editResellerRates = "/reseller/edit-reseller-rates",
}

export { routeMapMini };
