enum routeMapMini {
  login = "/login",
  dashboard = "/dashboard",
  payin = "/payin",
  settlement = "/settlement",
  payout = "/payout",
  technical = "/technical",
  merchantManagement = "/merchant-management",
  complainceSecurity = "/complaince-security",
  reseller = "/reseller",
  reports = "/reports",
  accessManagement = "/access-management",
  detailedTransactions = "/payin/detailed-transactions",
  updateTransactions = "/payin/update-transactions",
  checkStatus = "/payin/check-status",
  detailedSettlementTransactions = "/settlement/detailed-settlement-transactions",
  bulkAdjustment = "/settlement/bulk-adjustment",
  chargebackRefund = "/settlement/chargeback-refund",
  settlementStatement = "/settlement/settlement-statement",
  myAccount = "/my-account",
  payoutDetailedTransactions = "/payout/detailed-transactions",
  accounts = "/payout/accounts",
  statement = "/payout/statement",
}

export { routeMapMini };
